/* Do not edit - Machine generated */
#ifndef _INC_REACTOS_BUILDNO
#define _INC_REACTOS_BUILDNO
#define KERNEL_VERSION_BUILD	20221126
#define KERNEL_VERSION_BUILD_STR	"20221126-rUNKNOWN"
#define KERNEL_VERSION_BUILD_RC	"20221126-rUNKNOWN\0"
#define KERNEL_RELEASE_RC	"0.2.6-RELEASE\0"
#define KERNEL_RELEASE_STR	"0.2.6-RELEASE"
#define KERNEL_VERSION_RC	"0.2.6-RELEASE\0"
#define KERNEL_VERSION_STR	"0.2.6-RELEASE"
#define REACTOS_DLL_VERSION_MAJOR	42
#define REACTOS_DLL_RELEASE_RC	"42.2.6-RELEASE\0"
#define REACTOS_DLL_RELEASE_STR	"42.2.6-RELEASE"
#define REACTOS_DLL_VERSION_RC	"42.2.6-RELEASE\0"
#define REACTOS_DLL_VERSION_STR	"42.2.6-RELEASE"
#endif
/* EOF */
